=== PVtig/MML/xml/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="OlRu"
  xmlns="OlRu"
  xmlns:ml="OlRu" elementFormDefault="qualified">

  <xsd:annotation>
    <xsd:documentation>
            This schema musical group details.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="list" type="Groups"></xsd:element>

  <xsd:complexType name="Groups">
    <xsd:sequence>
      <xsd:element name="band" type="Group" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Group">
    <xsd:sequence>
      <xsd:element name="logo" type="xsd:string"></xsd:element>
      <xsd:element name="title" type="xsd:string"></xsd:element>
      <xsd:element name="genres" type="xsd:string"></xsd:element>
      <xsd:element name="briefSummary" type="xsd:string"></xsd:element>
      <xsd:element name="country">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="USA" />
            <xsd:enumeration value="UK" />
            <xsd:enumeration value="PL" />
            <xsd:enumeration value="AU" />
            <xsd:enumeration value="AT" />
            <xsd:enumeration value="GR" />
            <xsd:enumeration value="GE" />
            <xsd:enumeration value="CZ" />
            <xsd:enumeration value="EE" />
            <xsd:enumeration value="UA" />
            <xsd:enumeration value="KR" />
            <xsd:enumeration value="TH" />
            <xsd:enumeration value="USSR" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>

      <xsd:element name="structure" type="Structure"></xsd:element>
      <xsd:element name="discography" type="Discography"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>


  
  <xsd:complexType name="Author">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"></xsd:element>
      <xsd:element name="surname" type="xsd:string"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>



  <xsd:complexType name="Structure">
    <xsd:sequence>
      <xsd:element name="artist" type="Artist" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>



  <xsd:complexType name="Artist">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"></xsd:element>
      <xsd:element name="country">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="USA" />
            <xsd:enumeration value="UK" />
            <xsd:enumeration value="PL" />
            <xsd:enumeration value="AU" />
            <xsd:enumeration value="AT" />
            <xsd:enumeration value="GR" />
            <xsd:enumeration value="GE" />
            <xsd:enumeration value="CZ" />
            <xsd:enumeration value="USA" />
            <xsd:enumeration value="EE" />
            <xsd:enumeration value="UA" />
            <xsd:enumeration value="KR" />
            <xsd:enumeration value="TH" />
            <xsd:enumeration value="USSR" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="dateOfBirth" type="xsd:date"></xsd:element>
      <xsd:element name="placeOfBirth" type="xsd:string"></xsd:element>
      <xsd:element name="singingVoice">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Tenor" />
            <xsd:enumeration value="Mezzo-soprano" />
            <xsd:enumeration value="Contralto" />
            <xsd:enumeration value="Soprano" />
            <xsd:enumeration value="Baritone" />
            <xsd:enumeration value="Bass" />
            <xsd:enumeration value="Nan" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="instruments" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>



  <xsd:complexType name="Discography">
    <xsd:sequence>
      <xsd:element name="album" type="Album" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>



  <xsd:complexType name="Album">
    <xsd:sequence>
      <xsd:element name="albumName" type="xsd:string"></xsd:element>
      <xsd:element name="year" type="xsd:date"></xsd:element>
      <xsd:element name="label" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
      <xsd:element name="songs" type="Song"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Song">
    <xsd:sequence>
      <xsd:element name="song" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== PVtig/MML/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="inde.xsl"?>


<list xmlns="OlRu"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="OlRu index.xsd" >

    <band >
        <logo>LinkinPark.jpg</logo>
        <title>Linkin Park</title>
        <genres>Rock</genres>
        <briefSummary>Linkin Park is an American rock band from Agoura Hills, California. 
            The band's current lineup comprises vocalist/rhythm guitarist/keyboardist Mike Shinoda, 
            lead guitarist Brad Delson, bassist Dave Farrell, DJ/turntablist Joe Hahn and drummer Rob Bourdon, 
            all of whom are founding members. Vocalists Mark Wakefield and Chester Bennington are former members 
            of the band. </briefSummary>
        <country>USA</country>

        <structure>
            <artist>
                <name> Chester Charles Bennington</name>
                <country>USA</country>
                <dateOfBirth>1976-03-20</dateOfBirth>
                <placeOfBirth>USA</placeOfBirth>
                <singingVoice>Tenor</singingVoice>
                <instruments>guitar</instruments>
            </artist>
            <artist>
                <name> Michael Kenji Shinoda</name>
                <country>USA</country>
                <dateOfBirth>1977-02-11</dateOfBirth>
                <placeOfBirth>USA</placeOfBirth>
                <singingVoice>Baritone</singingVoice>
                <instruments>guitar</instruments>
            </artist>
            <artist>
                <name> David Michael Farrell</name>
                <country>USA</country>
                <dateOfBirth>1977-02-08</dateOfBirth>
                <placeOfBirth>USA</placeOfBirth>
                <singingVoice>Nan</singingVoice>
                <instruments>guitar</instruments>
            </artist>
            <artist>
                <name> Bradford Phillip "Brad" Delson</name>
                <country>USA</country>
                <dateOfBirth>1977-12-01</dateOfBirth>
                <placeOfBirth>USA</placeOfBirth>
                <singingVoice>Nan</singingVoice>
                <instruments>guitar</instruments>
            </artist>
            <artist>
                <name> Joseph «Joe» Hahn</name>
                <country>USA</country>
                <dateOfBirth>1977-03-15</dateOfBirth>
                <placeOfBirth>USA</placeOfBirth>
                <singingVoice>Nan</singingVoice>
                <instruments>Keyboard musical instruments</instruments>
            </artist>
        </structure>

        <discography>
            <album>
                <albumName> Hybrid Theory </albumName>
                <year>2000-01-01</year>
                <label>Warner Brothers Records</label>
                <songs>
                    <song>'Papercut' </song>
                    <song>'One Step Closer' </song>
                    <song>'With You' </song>
                    <song>'Points of Authority' </song>
                    <song>'Crawling' </song>
                    <song>'Runaway' </song>
                    <song>'By Myself' </song>
                    <song>'In the End' </song>
                    <song>'A Place for My Head' </song>
                    <song>'Forgotten' </song>
                    <song>'Cure for the Itch' </song>
                    <song>'Pushing Me Away' </song>
                </songs>
            </album>
            <album>

                <albumName>	Meteora </albumName>
                <year>2003-02-02</year>
                <label>Warner Brothers Records</label>
                <songs>
                    <song>'Foreword' </song>
                    <song>'Don't Stay' </song>
                    <song>'Somewhere I Belong' </song>
                    <song>'Lying from You' </song>
                    <song>'Hit the Floor' </song>
                    <song>'Easier to Run' </song>
                    <song>'Faint' </song>
                    <song>'Figure.09' </song>
                    <song>'Breaking the Habit' </song>
                    <song>'From the Inside' </song>
                    <song>'Nobody's Listening' </song>
                    <song>'Session' </song>
                    <song>'Numb' </song>
                </songs>
            </album>
            <album>

                <albumName>	Minutes to Midnight </albumName>
                <year>2007-02-02</year>
                <label>Warner Brothers Records/Machine Shop Recordings</label>
                <songs>
                    <song>'Wake' </song>
                    <song>'Given Up' </song>
                    <song>'Leave Out All the Rest' </song>
                    <song>'Bleed It Out' </song>
                    <song>'Shadow of the Day' </song>
                    <song>'What I’ve Done' </song>
                    <song>'Hands Held High' </song>
                    <song>'No More Sorrow' </song>
                    <song>'Valentine's Day' </song>
                    <song>'In Between' </song>
                    <song>'In Pieces' </song>
                    <song>'The Little Things Give You Away' </song>
                </songs>
            </album>
        </discography>
    </band>
    <band >
        <logo>BP.jpg</logo>
        <title>BLACKPINK</title>
        <genres>K-pop</genres>
        <briefSummary> Since their debut, Blackpink have 
        emerged as a prominent act in K-pop and have been described as the 
        "biggest girl group in the world", "biggest K-pop girl band on the planet",
        and "K-pop Queens". They have gained immense popularity in South Korea, 
        with Forbes Korea Power Celebrity named Blackpink the most powerful celebrities in 
        South Korea in 2019, 
        third in 2020, and second in 2021.
        </briefSummary>
        <country>KR</country>

        <structure>
            <artist>
                <name> Kim Ji Soo</name>
                <country>KR</country>
                <dateOfBirth>1995-01-03</dateOfBirth>
                <placeOfBirth>KR</placeOfBirth>
                <singingVoice>Mezzo-soprano</singingVoice>
                <instruments>-</instruments>
            </artist>
            <artist>
                <name> Kim jennie</name>
                <country>KR</country>
                <dateOfBirth>1996-01-16</dateOfBirth>
                <placeOfBirth>KR</placeOfBirth>
                <singingVoice>Mezzo-soprano</singingVoice>
                <instruments>-</instruments>
            </artist>
            <artist>
                <name> Park Chae Young</name>
                <country>KR</country>
                <dateOfBirth>1997-02-11</dateOfBirth>
                <placeOfBirth>KR</placeOfBirth>
                <singingVoice>Soprano</singingVoice>
                <instruments>-</instruments>
            </artist>
            <artist>
                <name> Lisa Manoban</name>
                <country>TH</country>
                <dateOfBirth>1997-03-17</dateOfBirth>
                <placeOfBirth>TH</placeOfBirth>
                <singingVoice>Mezzo-soprano</singingVoice>
                <instruments>-</instruments>
            </artist>
        </structure>
        <discography>
            <album>

                <albumName> Square Up </albumName>
                <year>2018-05-15</year>
                <label>YG Entertainment</label>
                <songs>
                    <song>'Ddu-Du Ddu-Du' </song>
                    <song>'Forever Young' </song>
                    <song>'Really' </song>
                    <song>'Bet You Wanna' </song>
                    <song>'Lovesick Girls' </song>
                    <song>'Bet You Wanna' </song>
                    <song>'Lovesick Girls' </song>
                    <song>'Bet You Wanna' </song>
                    <song>'Lovesick Girls' </song>
                    <song>'See U Later' </song>
                </songs>
            </album>
            <album>

                <albumName>	Kill This Love</albumName>
                <year>2019-02-02</year>
                <label>YG Entertainment</label>
                <songs>
                    <song>'Kill This Love' </song>
                    <song>'Don't Know What to Do' </song>
                    <song>'Kick It' </song>
                    <song>'Bet You Wanna' </song>
                    <song>'Lovesick Girls' </song>
                    <song>'Bet You Wanna' </song>
                    <song>'Lovesick Girls' </song>
                    <song>'Bet You Wanna' </song>
                    <song>'Lovesick Girls' </song>
                    <song>'Hope Not' </song>
                    <song>'Ddu-Du Ddu-Du' </song>
                </songs>
            </album>
            <album>

                <albumName>	The Album </albumName>
                <year>2020-02-02</year>
                <label>YG Entertainment</label>
                <songs>
                    <song>'How You Like That' </song>
                    <song>'Ice Cream' </song>
                    <song>'Pretty Savage' </song>
                    <song>'Bet You Wanna' </song>
                    <song>'Lovesick Girls' </song>
                    <song>'Crazy Over You' </song>
                    <song>'Love to Hate Me' </song>
                    <song>'You Never Know' </song>
                </songs>
            </album>
            <album>

                <albumName>	The Alb </albumName>
                <year>2020-02-02</year>
                <label>YG Entertainment</label>
                <songs>
                    <song>'How You Like That' </song>
                    <song>'Ice Cream' </song>
                    <song>'Pretty Savage' </song>
                    <song>'Bet You Wanna' </song>
